Try to explain purpose of monads
bridgefield/bits pull request #14
Opened 2022-05-04 17:36 UTC by Dirk-Peters

2022-05-25 08:54 UTC, jasie commented on README.md
> +See [Monads](./documentation/monads.md) to explain the purpose of monads in general, and the implementations in this repositories.
in **these** repositories

2022-05-25 08:54 UTC, jasie commented on documentation/monads.md
> +## What ist it
What **is** it

2022-05-25 08:54 UTC, jasie commented on documentation/monads.md
> +The basic idea for using monads is to ``elevate`` a value at the start of a contiguous peace of functionality,
peace -> piece

2022-05-25 08:54 UTC, jasie commented on documentation/monads.md
> +with ``sequences`` instead of single values.
Ich fand die zusammenfassung von AP hilfreich: "easy to get in, difficult to get out"

2022-05-25 08:54 UTC, jasie commented on documentation/monads.md
> +resulting value again, to either persist, show to a user or provide as input for other functions not working with the
user**,** or provide

2022-05-25 08:54 UTC, jasie commented on documentation/monads.md
> +In order to this a ``match`` operation is used. The signature of this operation depends on the actual monad type but in
**For this purpose** a ``match`` operation ...

2022-05-25 08:54 UTC, jasie commented on documentation/monads.md
> +``IEnumerable``, ``IQueryable`` and ``IObservable`` implementations can all be considered monads.
sehr nützliche anmerkung!

2022-05-25 08:54 UTC, jasie commented on documentation/monads.md
> +Long story short: every generic type, that can be supplied with ``SelectMany`` overloads is very likely a Monad.
bitte für eine schreibweise entscheiden: **M**onad oder **m**onad (vereinheitlichen)

2022-05-25 08:54 UTC, jasie commented on documentation/monads.md
> +TODO: LINQ, composition ...
entweder noch das TODO schreiben oder ohne den abschnitt mergen IMHO

2022-05-25 08:54 UTC, jasie commented on documentation/monads.md
> +
ich fände einen abschnitt über 'how to unit test monads' sehr hilfreich
(vielleicht auch im vergleich - mit und ohne monad)

2022-05-25 08:54 UTC, jasie commented on documentation/monads.md
> +
ich fand das lightsaber code beispiel von AP nützlich: einmal mit und ohne monade im vergleich, inkl. bind und unpack

2022-05-25 09:09 UTC, Dirk-Peters-BF commented on documentation/monads.md
> +## What is this library about?
```suggestion
## What is MonadicBits about?
```

2022-05-25 09:13 UTC, Dirk-Peters-BF commented on documentation/monads.md
> +All in all this minimizes the possibility of ``lying`` signatures.
move comment about "lying signatures" to start of chapter about MonadicBits

2022-05-25 09:13 UTC, Dirk-Peters-BF commented on documentation/monads.md
> +## What is this library about?
short overview about included monads + purpose

2022-06-19 12:15 UTC, apfohl requested changes

2022-06-19 12:15 UTC, apfohl commented on documentation/monads.md
> +public static Either<Maybe<string>,Error> Foo(){
Swap type parameters of Either.

2022-06-27 08:39 UTC, apfohl commented
What do you guys think about getting this merged and move on in another PR? I really like the changes to the docs at this point and would like tho have them public.

@jasie @Dirk-Peters @Dirk-Peters-BF

2022-06-27 08:42 UTC, apfohl commented on documentation/monads.md
> +
I created #16 to work this in.

2022-06-27 08:44 UTC, apfohl commented on documentation/monads.md
> +
Maybe we should have some examples alongside the code. #17

2022-06-27 08:45 UTC, apfohl approved these changes

2022-06-27 08:49 UTC, apfohl commented
Sorry, I rebased the branch on main.

2022-07-05 13:17 UTC, merged